# Generated by Django 4.0.4 on 2022-05-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_wallets_usd_value_alter_wallets_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchains', models.TextField()),
                ('tokens', models.TextField()),
                ('USD_value', models.FloatField()),
                ('balance', models.FloatField()),
                ('prices', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
