# Generated by Django 4.0.4 on 2022-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_historiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiques',
            name='PdP',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallets',
            name='PdP',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
