# Generated by Django 4.0.4 on 2022-05-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ff',
        ),
    ]
